logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#配置rmq
spring:
  rabbitmq:
    host: 127.0.0.1 # 主机名
    port: 5672 # 端口
    virtual-host: / # 虚拟主机
    username: guest # 用户名
    password: guest # 密码
    #控制预取消费的上限
    prefetch: 1 # 每次只能获取一条消息，处理完成才能获取下一个消息